// export const SUBJECTS = [
// 	"Astronomy",
// 	"Biology",
// 	"Biomedical Sciences",
// 	"Chemistry Earth",
// 	"Sciences",
// 	"Environmental Sciences",
// 	"Food Science and Technology",
// 	"Forensic science",
// 	"General Sciences",
// 	"Life Sciences",
// 	"Materials Sciences",
// 	"Mathematics",
// 	"Physical Geography",
// 	"Physics",
// 	"Sports Science",
// 	"Architecture",
// 	"Built Environment",
// 	"Construction",
// 	"Maintenance Services",
// 	"Planning",
// 	"Property Management",
// 	"Surveying",
// 	"Computer Science",
// 	"Computing",
// 	"IT",
// 	"Multimedia",
// 	"Software",
// 	"Aerospace Engineering",
// 	"Biomedical Engineering",
// 	"Chemical and Materials Engineering",
// 	"Civil Engineering",
// 	"Electrical Engineering",
// 	"Electronic Engineering",
// 	"Environmental Engineering",
// 	"General Engineering and Technology",
// 	"Manufacturing and Production",
// 	"Marine Engineering",
// 	"Mechanical Engineering",
// 	"Metallurgy",
// 	"Mining and Oil & Gas Operations",
// 	"Power and Energy Engineering",
// 	"Quality Control",
// 	"Structural Engineering",
// 	"Telecommunications",
// 	"Vehicle Engineering",
// ];

export const SUBJECTS = [
	"Астрономия",
	"Биология",
	"Биомедицинские науки",
	"Химия",
	"Науки о Земле",
	"Экологические науки",
	"Наука о продуктах питания и технологиях",
	"Судебная экспертиза",
	"Общие науки",
	"Науки о жизни",
	"Материаловедение",
	"Математика",
	"Физическая география",
	"Физика",
	"Спортивная наука",
	"Архитектура",
	"Застроенная среда",
	"Строительство",
	"Службы обслуживания",
	"Планирование",
	"Управление недвижимостью",
	"Съемка",
	"Компьютерные науки",
	"Вычислительная техника",
	"Информационные технологии",
	"Мультимедиа",
	"Программное обеспечение",
	"Аэрокосмическая инженерия",
	"Биомедицинская инженерия",
	"Химическая и материаловедческая инженерия",
	"Гражданская инженерия",
	"Электротехника",
	"Электронная инженерия",
	"Экологическая инженерия",
	"Общая инженерия и технологии",
	"Производство и производство",
	"Морская инженерия",
	"Механическая инженерия",
	"Металлургия",
	"Горные и нефтегазовые операции",
	"Энергетическая инженерия",
	"Контроль качества",
	"Структурная инженерия",
	"Телекоммуникации",
	"Автомобильная инженерия",
];

export default {
	SUBJECTS,
};
