export const SUBJECTS = [
	"Astronomy",
	"Biology",
	"Biomedical Sciences",
	"Chemistry Earth",
	"Sciences",
	"Environmental Sciences",
	"Food Science and Technology",
	"Forensic science",
	"General Sciences",
	"Life Sciences",
	"Materials Sciences",
	"Mathematics",
	"Physical Geography",
	"Physics",
	"Sports Science",
	"Architecture",
	"Built Environment",
	"Construction",
	"Maintenance Services",
	"Planning",
	"Property Management",
	"Surveying",
	"Computer Science",
	"Computing",
	"IT",
	"Multimedia",
	"Software",
	"Aerospace Engineering",
	"Biomedical Engineering",
	"Chemical and Materials Engineering",
	"Civil Engineering",
	"Electrical Engineering",
	"Electronic Engineering",
	"Environmental Engineering",
	"General Engineering and Technology",
	"Manufacturing and Production",
	"Marine Engineering",
	"Mechanical Engineering",
	"Metallurgy",
	"Mining and Oil & Gas Operations",
	"Power and Energy Engineering",
	"Quality Control",
	"Structural Engineering",
	"Telecommunications",
	"Vehicle Engineering",
];
export default {
	SUBJECTS,
};
